language: python
env:
- TOXENV=py34
- TOXENV=py35
install: pip install -U tox
script: tox
deploy:
  provider: pypi
  distributions: sdist
  user: rhgrant10
  password:
    secure: JhxeEKGlDqtxzJrHoRqa9YFuEWbQOhH3/maVjdqLH/LXpfKEcYq7K1hZRYOATaIVJ+Y0dZJ0IKJrRfAP1IgMXphySDe8GwbNyt7ifngUru+tyvZ5gGs7mGbI4Z6Jev58zf0h+laiNMj7EmqBcEJZ6e4fy2jardCspUJ3/EGC87E=
  on:
    tags: true
    repo: rhgrant10/Groupy
    condition: $TOXENV == py35
